spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: your_password
    url: jdbc:mysql://your_ip:3306/hblog?serverTimezone=Asia/Shanghai
  redis:
    host: your_ip
    password: your_password
    port: 6379
    database: 0
    timeout: 10000ms
