spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/hblog?serverTimezone=Asia/Shanghai
  redis:
    host: localhost
    password:
    port: 6379
    database: 0
    timeout: 10000ms

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com # Endpoint以华东1（杭州）为例，其它Region请按实际情况填写。
    bucketName: yourBucketName # Bucket名称
    custom-domain: https://yourCustomDomain.com # 自定义域名
    access-key-id: yourKey
    access-key-secret: yourSecret

AI:
  Qianfan: # 百度千帆
    accessKey: xxxxxxxx # 百度千帆的accessKey
    secretKey: xxxxxxxx # 百度千帆的secretKey