spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: your_password
    url: jdbc:mysql://your_ip:3306/hblog?serverTimezone=Asia/Shanghai&useSSL=false
  redis:
    host: your_ip
    password: your_password
    port: 6379
    database: 0
    timeout: 10000ms

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com # Endpoint以华东1（杭州）为例，其它Region请按实际情况填写。
    bucketName: yourBucketName # Bucket名称
    custom-domain: https://yourCustomDomain.com # 自定义域名
    access-key-id: yourKey
    access-key-secret: yourSecret

server:
  ssl:
    key-store: classpath:xxxxx.pfx
    key-store-type: xxxxx
    key-store-password: xxxxx